Soru 1 – Liste Metotları 

Bir sınıfta öğrencilerin notları şu şekilde tutuluyor: 

notlar = [85, 92, 76, 92, 100, 76, 85, 92] 

• Listedeki tekrar eden notları silip benzersiz bir 
liste oluşturun. 

• En yüksek ve en düşük notu bulun. 

• Notları küçükten büyüğe sıralayın.

In [1]:

notlar = [85, 92, 76, 92, 100, 76, 85, 92]

benzersiz_notlar = list(set(notlar))
print("Benzersiz Notlar:", benzersiz_notlar)

en_yuksek_not = max(notlar)
en_dusuk_not = min(notlar)
print("En Yüksek Not:", en_yuksek_not)
print("En Düşük Not:", en_dusuk_not)

sıralı_notlar = sorted(notlar)
print("Notlar Küçükten Büyüğe Sıralanmış:", sıralı_notlar)

Benzersiz Notlar: [100, 92, 85, 76]
En Yüksek Not: 100
En Düşük Not: 76
Notlar Küçükten Büyüğe Sıralanmış: [76, 76, 85, 85, 92, 92, 92, 100]


Soru 2 – Sayılar 

Bir sayının Armstrong sayısı olup olmadığını kontrol 
eden bir Python fonksiyonu yazın. 

Armstrong sayısı: Her basamağının küplerinin toplamı 
kendisine eşit olan sayılar. 

Örn: 153 → 1³+5³+3³ = 153

In [ ]:
def armstrong_sayisi_mi(sayi):
    rakamlar = [int(rakam) for rakam in str(sayi)]
    toplam = sum(rakam ** 3 for rakam in rakamlar)
    return toplam == sayi
sayi = int(input("Bir sayı girin: "))
if armstrong_sayisi_mi(sayi):
    print(f"{sayi} bir Armstrong sayısıdır.")
else:
    print(f"{sayi} bir Armstrong sayısı değildir.")


153 bir Armstrong sayısıdır.


Soru 3 – Kümeler 

Aşağıdaki iki küme verilmiştir: 

A = {"Python", "R", "SQL", "Java"} 

B = {"C++", "Python", "JavaScript", "SQL"} 

• Ortak dilleri bulun. 

• Sadece A’da olan dilleri listeleyin. 

• İki kümenin birleşimini alfabetik olarak yazdırın.

In [ ]:
A = {"Python", "R", "SQL", "Java"}
B = {"C++", "Python", "JavaScript", "SQL"}
ortak_diller=[]
for dil in A:
    if dil in B:
        ortak_diller.append(dil)
print("Ortak Diller:", ortak_diller)
sadece_A_dilleri = list(A - B)
print("Sadece A'da Olan Diller:", sadece_A_dilleri)
birlesim = sorted(A | B)
print("İki Kümenin Birleşimi (Alfabetik):", birlesim)


Ortak Diller: ['Python', 'SQL']
Sadece A'da Olan Diller: ['R', 'Java']
İki Kümenin Birleşimi (Alfabetik): ['C++', 'Java', 'JavaScript', 'Python', 'R', 'SQL']


Soru 4 – Modüller 

• random modülünü kullanarak 1–100 arasında 10 rastgele sayı üretin. 

• Bu sayıların ortalamasını ve standart sapmasını statistics modülü ile hesaplayın.

In [ ]:

import random
rastgele_sayilar = [random.randint(1, 100) for _ in range(10)]
ortalama = sum(rastgele_sayilar) / len(rastgele_sayilar)
import statistics
standart_sapma = statistics.stdev(rastgele_sayilar)
print("Rastgele Sayılar:", rastgele_sayilar)
print("Ortalama:", ortalama)
print("Standart Sapma:", standart_sapma)

Rastgele Sayılar: [79, 14, 30, 99, 55, 39, 75, 47, 13, 76]
Ortalama: 52.7
Standart Sapma: 29.23107174832212


Soru 5 – Fonksiyonlar 

kelime_sayacı(metin) adında bir fonksiyon yazın. 

Fonksiyon verilen metindeki: 

• toplam kelime sayısını 

• en uzun kelimeyi 

• en sık geçen kelimeyi döndürsün.

In [ ]:
def kelime_sayaci(metin):
    kelimeler = metin.split()
    toplam_kelime_sayisi = len(kelimeler)
    en_uzun_kelime = max(kelimeler, key=len)
    kelime_tekrarı = {}
    for kelime in kelimeler:
        kelime_tekrarı[kelime] = kelime_tekrarı.get(kelime, 0) + 1
    en_sik_gecen_kelime = max(kelime_tekrarı, key=kelime_tekrarı.get)
    return toplam_kelime_sayisi, en_uzun_kelime, en_sik_gecen_kelime
metin = "Yaz Kampı: Veri bilimine giriş 1. sınıf öğrencisiyim. Veri bilimini öğreniyorum."
toplam, en_uzun, en_sik = kelime_sayaci(metin)
print("Toplam Kelime Sayısı:", toplam)
print("En Uzun Kelime:", en_uzun)
print("En Sık Geçen Kelime:", en_sik)



Toplam Kelime Sayısı: 11
En Uzun Kelime: öğrencisiyim.
En Sık Geçen Kelime: Veri


Soru 6 – Gömülü Fonksiyonlar 

Aşağıdaki liste için map, filter, sorted gibi gömülü 
fonksiyonları kullanarak: 

sayilar = [5, 12, 7, 18, 24, 3, 16] 

• Sadece çift sayıları filtreleyin. 

• Bu sayıların karelerini bulun. 

• Karelerini azalan sırada sıralayın.

In [ ]:
sayilar = [5, 12, 7, 18, 24, 3, 16]
cift_sayilar = list(filter(lambda x: x % 2 == 0, sayilar))
print("Çift Sayılar:", cift_sayilar)
kareler = list(map(lambda x: x ** 2, sayilar))
print("Kareler:", kareler)
sirali_kareler = sorted(kareler, reverse=True)
print("Kareler Azalan Sırada:", sirali_kareler)


Çift Sayılar: [12, 18, 24, 16]
Kareler: [25, 144, 49, 324, 576, 9, 256]
Kareler Azalan Sırada: [576, 324, 256, 144, 49, 25, 9]


Soru 7 – Lambda İfadeleri 

Aşağıdaki listeyi, her kelimenin uzunluğuna göre 
küçükten büyüğe sıralayın. 

kelimeler = ["veri", "bilim", "analiz", "yapayzeka", 
"python"] 

Bunu sorted + lambda ile yapın.

In [ ]:

kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "python"]
sirali_kelimeler = sorted(kelimeler, key=lambda x: len(x))
print("Kelimeler Uzunluklarına Göre Sıralanmış:", sirali_kelimeler)


Kelimeler Uzunluklarına Göre Sıralanmış: ['veri', 'bilim', 'analiz', 'python', 'yapayzeka']


Soru 8 – Metodlar 

Bir string içinde geçen tüm rakamları bulun ve bunların toplamını döndüren bir fonksiyon yazın. 

Örn: "abc12def3" → 12 + 3 = 15 

In [17]:
"""Soru 8 – Metodlar 
Bir string içinde geçen tüm rakamları bulun ve bunların toplamını döndüren bir fonksiyon 
yazın. 
Örn: "abc12def3" → 12 + 3 = 15 """
def rakam_toplami(metin):
    rakamlar = [int(char) for char in metin if char.isdigit()]
    return sum(rakamlar)
metin = "abc12def3454"
toplam = rakam_toplami(metin)
print("Rakamların Toplamı:", toplam)



Rakamların Toplamı: 19


Soru 9 – (Ekstra) Numpy 1  

10 elemanlı bir numpy dizisi oluşturun. 

• Elemanlar 0–50 arasında rastgele sayılar olsun. 

• Dizinin ortalamasını, standart sapmasını ve en büyük değerini bulun.

In [19]:
!pip install numpy

  Using cached numpy-2.3.2-cp313-cp313-win_amd64.whl.metadata (60 kB)
Using cached numpy-2.3.2-cp313-cp313-win_amd64.whl (12.8 MB)


In [20]:
"""Soru 9 – (Ekstra) Numpy 1  
10 elemanlı bir numpy dizisi oluşturun. 
• Elemanlar 0–50 arasında rastgele sayılar olsun. 
• Dizinin ortalamasını, standart sapmasını ve en büyük değerini bulun."""
import numpy as np
dizi = np.random.randint(0, 51, size=10)
ortalama = np.mean(dizi)
standart_sapma = np.std(dizi)
en_buyuk = np.max(dizi)
print("Numpy Dizisi:", dizi)
print("Ortalama:", ortalama)
print("Standart Sapma:", standart_sapma)
print("En Büyük Değer:", en_buyuk)


Numpy Dizisi: [37 26  3 41 48 42 13  6 26 22]
Ortalama: 26.4
Standart Sapma: 14.82700239428051
En Büyük Değer: 48


Soru 10 – (Ekstra) Numpy 2 

5x5 boyutunda rastgele 0–1 arasında değerlerden oluşan bir numpy matrisi üretin. 

• Her sütunun ortalamasını bulun. 

• 0.5’ten büyük olan değerleri 1, küçük eşit olanları 0 yaparak binary matris oluşturun.

In [21]:
"""Soru 10 – (Ekstra) Numpy 2 
5x5 boyutunda rastgele 0–1 arasında değerlerden oluşan bir numpy matrisi üretin. 
• Her sütunun ortalamasını bulun. 
• 0.5’ten büyük olan değerleri 1, küçük eşit olanları 0 yaparak binary matris oluşturun."""
import numpy as np
matris = np.random.rand(5, 5)
sutun_ortalamalari = np.mean(matris, axis=0)
binary_matris = np.where(matris > 0.5, 1, 0)
print("Orijinal Matris:\n", matris)
print("Sütun Ortalamaları:", sutun_ortalamalari)
print("Binary Matris:\n", binary_matris)


Orijinal Matris:
 [[0.34836919 0.59241589 0.62795149 0.14381686 0.89661604]
 [0.11082102 0.64590141 0.54163829 0.6483246  0.06394091]
 [0.0667201  0.99620363 0.95833045 0.94030112 0.47626529]
 [0.30988413 0.51085492 0.96586748 0.27722296 0.09933217]
 [0.86596847 0.88140378 0.42638655 0.59536589 0.9739308 ]]
Sütun Ortalamaları: [0.34035258 0.72535593 0.70403485 0.52100629 0.50201704]
Binary Matris:
 [[0 1 1 0 1]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 0 0]
 [1 1 0 1 1]]


    Proje – “Kitap Satış Analiz Sistemi” 
Bir yayınevinin farklı türlerde ve yazarlarda kitapları var. 
    Örnek veri: 
kitaplar = [ 

{"isim": "Veri Bilimi 101", "yazar": "Ali", "tur": "Bilim", "satis": 1200, "yil": 2021}, 

{"isim": "Python ile Yapay Zeka", "yazar": "Ayşe", "tur": "Bilim", "satis": 950, "yil": 
2020}, 

{"isim": "İstatistik Temelleri", "yazar": "Ali", "tur": "Akademik", "satis": 700, "yil": 2019}, 

{"isim": "Makine Öğrenmesi", "yazar": "Can", "tur": "Bilim", "satis": 1800, "yil": 2022}, 

{"isim": "Veri Görselleştirme", "yazar": "Deniz", "tur": "Sanat", "satis": 400, "yil": 2018}, 

{"isim": "Matematiksel Modelleme", "yazar": "Ali", "tur": "Akademik", "satis": 1500, 
"yil": 2021}, 

{"isim": "Bilgi Toplumu", "yazar": "Ayşe", "tur": "Sosyal", "satis": 600, "yil": 2022} 
]

    Yapılması Gerekenler: 
1. Fonksiyon Yazma: 
    en_cok_satan(kitaplar) → En çok satan kitabın bilgilerini döndürsün. 
    
    yazar_satislari(kitaplar) → Her yazarın toplam satışını bir sözlük olarak döndürsün. 

2. Liste ve Küme İşlemleri: 
    Tüm kitap türlerini (tur) küme halinde çıkarın (tekrar eden türler olmadan). 
    
    Satış adedi 1000’den fazla olan kitapların isimlerini bir listede toplayın. 

3. Lambda / Filter / Map Kullanımı: 
    filter ile 2020’den sonra çıkan kitapları süzün. 
    
    map ile tüm satış adetlerini %10 artırılmış şekilde yeni bir listeye aktarın. 
    
    sorted + lambda ile kitapları satış miktarına göre azalan şekilde sıralayın. 

4. İstatistiksel Analiz: 
    Ortalama satış adedini bulun. 
    
    En çok satış yapan türü bulun. 
    
    Satışların standart sapmasını hesaplamak için statistics modülünü kullanın. 

5. Ekstra (Zorlayıcı): Train/Test Simülasyonu 
    Kitap listesini rastgele %70 eğitim (train), %30 test verisine ayırın 
    (random.sample). 

    Eğitim verisinden yazarların ortalama satışını hesaplayın. 

    Test verisinde, hangi kitapların satışlarının bu ortalamanın üzerinde olduğunu kontrol edin. 

---- Beklenen Çıktı Örneği ---- 
• En çok satan kitap: "Makine Öğrenmesi" 

• Yazar satışları: {"Ali": 3400, "Ayşe": 1550, "Can": 1800, "Deniz": 400} 

• Türler: {"Bilim", "Akademik", "Sanat", "Sosyal"} 

• 1000’den fazla satan kitaplar: ["Veri Bilimi 101", "Makine Öğrenmesi", 
"Matematiksel Modelleme"] 

• Ortalama satış: 1021.4 

• Standart sapma: ~480.2 

• Eğitim/ Test ayırımı sonrası analiz: 

---- Analizde Sizden Beklenen: ---- 
• Veriyi uygun oranlarda ayırın (örneğin %70 train, %30 test). 

• Train seti üzerinde basit analizler yapın (ortalama, sıklık, vs.). 

• Test seti üzerinde aynı analizleri tekrarlayın. 

• Sonuçları karşılaştırın ve kısa yorum ekleyin.

In [36]:

kitaplar = [ 
{"isim": "Veri Bilimi 101", "yazar": "Ali", "tur": "Bilim", "satis": 1200, "yil": 2021}, 
{"isim": "Python ile Yapay Zeka", "yazar": "Ayşe", "tur": "Bilim", "satis": 950, "yil": 2020}, 
{"isim": "İstatistik Temelleri", "yazar": "Ali", "tur": "Akademik", "satis": 700, "yil": 2019}, 
{"isim": "Makine Öğrenmesi", "yazar": "Can", "tur": "Bilim", "satis": 1800, "yil": 2022}, 
{"isim": "Veri Görselleştirme", "yazar": "Deniz", "tur": "Sanat", "satis": 400, "yil": 2018}, 
{"isim": "Matematiksel Modelleme", "yazar": "Ali", "tur": "Akademik", "satis": 1500, "yil": 2021}, 
{"isim": "Bilgi Toplumu", "yazar": "Ayşe", "tur": "Sosyal", "satis": 600, "yil": 2022} 
]

def en_cok_satan(kitaplar):
    return max(kitaplar, key=lambda x: x["satis"])
en_cok_satan_kitap = en_cok_satan(kitaplar)
print("En Çok Satan Kitap:", en_cok_satan_kitap["isim"])

def yazar_satislari(kitaplar):
    satis_dict = {}
    for kitap in kitaplar:
        yazar = kitap["yazar"]
        satis = kitap["satis"]
        satis_dict[yazar] = satis_dict.get(yazar, 0) + satis
    return satis_dict
yazar_satis = yazar_satislari(kitaplar)
print("\nYazar Satışları:", yazar_satis)
tum_turler = set(kitap["tur"] for kitap in kitaplar)

print("\nTüm Kitap Türleri:", tum_turler)

satis_1000_ustu = [kitap for kitap in kitaplar if kitap["satis"] > 1000]
print("\n1000'den Fazla Satan Kitapların Satış Sayıları:", {kitap["isim"]: kitap["satis"] for kitap in satis_1000_ustu})

kitaplar_2020_sonrasi = list(filter(lambda x: x["yil"] > 2020, kitaplar))
print("\n2020'den Sonra Çıkan Kitaplar:", [kitap["isim"] for kitap in kitaplar_2020_sonrasi])

satis_artirilmis = list(map(lambda x: {**x, "satis": int(x["satis"] * 1.1)}, kitaplar))
print("\nSatışları %10 Artırılmış Kitaplar:", [{kitap["isim"]: kitap["satis"]} for kitap in satis_artirilmis])    
sirali_kitaplar = sorted(kitaplar, key=lambda x: x["satis"], reverse=True)
print("\nKitaplar Satış Miktarına Göre Azalan Sırada:", [{kitap["isim"]: kitap["satis"]} for kitap in sirali_kitaplar])   

import statistics
ortalama_satis = statistics.mean(kitap["satis"] for kitap in kitaplar)
print("\nOrtalama Satış Adedi:", ortalama_satis)
tur_satislari = {}
for kitap in kitaplar:
    tur = kitap["tur"]
    satis = kitap["satis"]
    tur_satislari[tur] = tur_satislari.get(tur, 0) + satis
en_cok_satan_tur = max(tur_satislari, key=tur_satislari.get)
print("\nEn Çok Satış Yapan Tür:", en_cok_satan_tur)
satis_sayilari = [kitap["satis"] for kitap in kitaplar]
satis_standart_sapma = statistics.stdev(satis_sayilari)
print("\nSatışların Standart Sapması:", satis_standart_sapma)
import random
train_size = int(0.7 * len(kitaplar))
train_set = random.sample(kitaplar, train_size)
test_set = [kitap for kitap in kitaplar if kitap not in train_set]
print("\nEğitim Seti:", [{kitap["isim"]: kitap["satis"]} for kitap in train_set])
print("\nTest Seti:", [{kitap["isim"]: kitap["satis"]} for kitap in test_set])
yazar_ortalama_satis = {}
for kitap in train_set:
    yazar = kitap["yazar"]
    satis = kitap["satis"]
    if yazar not in yazar_ortalama_satis:
        yazar_ortalama_satis[yazar] = []
    yazar_ortalama_satis[yazar].append(satis)
for yazar in yazar_ortalama_satis:
    yazar_ortalama_satis[yazar] = statistics.mean(yazar_ortalama_satis[yazar])
print("\nYazarların Ortalama Satışları (Eğitim Seti):", yazar_ortalama_satis)
ortalama_satis_egitim = statistics.mean(yazar_ortalama_satis.values())
print("\nEğitim Seti Ortalama Satış:", ortalama_satis_egitim)

def set_analiz(kitap_listesi):
    ort_satis = statistics.mean([k["satis"] for k in kitap_listesi])
    yazarlar = {}
    turler = {}
    for k in kitap_listesi:
        yazarlar[k["yazar"]] = yazarlar.get(k["yazar"], 0) + k["satis"]
        turler[k["tur"]] = turler.get(k["tur"], 0) + k["satis"]
    en_cok_yazar = max(yazarlar, key=yazarlar.get)
    en_cok_tur = max(turler, key=turler.get)
    return ort_satis, en_cok_yazar, en_cok_tur

train_ort, train_yazar, train_tur = set_analiz(train_set)
test_ort, test_yazar, test_tur = set_analiz(test_set)

print("\n--- Eğitim Seti Analizi ---")
print("Ortalama Satış:", train_ort)
print("En Çok Satan Yazar:", train_yazar)
print("En Çok Satan Tür:", train_tur)

print("\n--- Test Seti Analizi ---")
print("Ortalama Satış:", test_ort)
print("En Çok Satan Yazar:", test_yazar)
print("En Çok Satan Tür:", test_tur)

print("\n--- Karşılaştırma ve Yorum ---")
if train_ort > test_ort:
    print("Eğitim setinin ortalama satışı test setinden yüksek. Eğitim setinde daha çok satan kitaplar olabilir.")
else:
    print("Test setinin ortalama satışı eğitim setinden yüksek. Test setinde popüler kitaplar olabilir.")
print("En çok satan yazar ve türler setler arasında değişiklik gösterebilir.")



En Çok Satan Kitap: Makine Öğrenmesi

Yazar Satışları: {'Ali': 3400, 'Ayşe': 1550, 'Can': 1800, 'Deniz': 400}

Tüm Kitap Türleri: {'Sosyal', 'Akademik', 'Sanat', 'Bilim'}

1000'den Fazla Satan Kitapların Satış Sayıları: {'Veri Bilimi 101': 1200, 'Makine Öğrenmesi': 1800, 'Matematiksel Modelleme': 1500}

2020'den Sonra Çıkan Kitaplar: ['Veri Bilimi 101', 'Makine Öğrenmesi', 'Matematiksel Modelleme', 'Bilgi Toplumu']

Satışları %10 Artırılmış Kitaplar: [{'Veri Bilimi 101': 1320}, {'Python ile Yapay Zeka': 1045}, {'İstatistik Temelleri': 770}, {'Makine Öğrenmesi': 1980}, {'Veri Görselleştirme': 440}, {'Matematiksel Modelleme': 1650}, {'Bilgi Toplumu': 660}]

Kitaplar Satış Miktarına Göre Azalan Sırada: [{'Makine Öğrenmesi': 1800}, {'Matematiksel Modelleme': 1500}, {'Veri Bilimi 101': 1200}, {'Python ile Yapay Zeka': 950}, {'İstatistik Temelleri': 700}, {'Bilgi Toplumu': 600}, {'Veri Görselleştirme': 400}]

Ortalama Satış Adedi: 1021.4285714285714

En Çok Satış Yapan Tür: Bilim

Satışların